### ISSUE TITLE
redhat enterprise - do we need to register?

### ISSUE THREAD

**Issue by sinanshi** [UCL-HIC/idhs-env#1]
@dpshelio 
I downloaded the vagrant redhat distribution for virtual box. To be able to use `yum` it requires the registration. I made my registration, however when I pull from the repos, it is still rejected. Do we need to pay for that? I have no idea about the Red hat. 

I am using centos instead for the moment.

**Comment by dpshelio** [comment]
We probably will need to use the UCL sattellite and registered to it. Will look into it soon.
